### ISSUE TITLE
meta author is [object Object]

### ISSUE THREAD

**Issue by pdehaan** [alexanderameye/personal-site#1]
```html
<meta name="author" content="[object Object]">
```

via https://github.com/alexanderameye/personal-site/blob/2b7c0ab3e4476db9f6b2b4677da021bf160d6b91/_includes/head.njk#L7

where `metadata.author` is an object:

https://github.com/alexanderameye/personal-site/blob/2b7c0ab3e4476db9f6b2b4677da021bf160d6b91/_data/metadata.json#L7-L11

So you'd need to do something like `metadata.author.name` or maybe have a custom filter that converts the `metadata.author` object to an npm package.json-like string:

```js
// https://docs.npmjs.com/cli/v7/configuring-npm/package-json#people-fields-author-contributors
{
  "author": "Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)"
}
```

**Comment by alexanderameye** [comment]
Fixed, thanks :)
